#!/bin/sh

#Copied from the runjags package.
rm -f .DS_Store
rm -f R/.DS_Store
rm -f inst/.DS_Store
rm -f man/.DS_Store
rm -rf R/.svn
rm -rf inst/.svn
rm -rf man/.svn
rm -f src/.DS_Store
rm -f src/distributions/.DS_Store

rm -rf src/.deps
rm -rf src/distributions/.deps
rm -rf src/distributions/.libs

rm -f src/Makevars
rm -f config.*
rm -rf autom4te.cache
rm -f config.log
rm -f config.status

rm -f src/runjags.o
rm -f src/testrunjags.o
rm -f src/runjags.so
rm -f src/symbols.rds

rm -f src/distributions/*.o
rm -f src/functions/*.o
rm -f src/distributions/jags/*.o

exit 0
